drop table plant;
drop table users;
drop table unit;
drop table hot_mix_test_result;
drop table recipe;

create table unit
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL UNIQUE
);

create table users
(
    id      int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name    varchar(30) NOT NULL,
    surname varchar(30) NOT NULL,
    position varchar(30) NOT NULL,
    login varchar(30) NOT NULL,
    password varchar(100) NOT NULL,
    roles varchar (100) NOT NULL,
    unit_id int REFERENCES unit(id) ON DELETE SET NULL
);

create table plant (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model varchar(30) NOT NULL,
    location varchar(30) NOT NULL,
    productivity int,
    unit_id int REFERENCES unit(id) ON DELETE SET NULL
);

create table hot_mix_test_result (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dno decimal(6,2),
    chog0063 decimal(6,2),
    chog0125 decimal(6,2),
    chog025 decimal(6,2),
    chog05 decimal(6,2),
    chog1 decimal(6,2),
    chog2 decimal(6,2),
    chog4 decimal(6,2),
    chog56 decimal(6,2),
    chog8 decimal(6,2),
    chog112 decimal(6,2),
    chog16 decimal(6,2),
    chog224 decimal(6,2),
    chog315 decimal(6,2),
    gmb decimal(4,3),
    gmm decimal(4,3)
);

create table recipe (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    stone_coarse1 varchar,
    stone_coarse2 varchar,
    stone_coarse3 varchar,
    stone_coarse4 varchar,
    stone_coarse5 varchar,
    stone_coarse6 varchar,
    stone_fine1 varchar,
    stone_fine2 varchar,
    powder varchar,
    bitumen varchar
);






