drop table plant;
drop table users;
drop table unit;

create table unit
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL UNIQUE
);

create table users
(
    id      int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name    varchar(30) NOT NULL,
    surname varchar(30) NOT NULL,
    unit_id int REFERENCES unit(id) ON DELETE SET NULL
);

create table plant (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model varchar(30) NOT NULL,
    location varchar(30) NOT NULL,
    productivity int
)






