drop table plant;
drop table users;
drop table unit;
drop table hot_mix_test_result;
drop table recipe;
drop table batch;

create table unit
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL UNIQUE
);

create table users
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     varchar(30)  NOT NULL,
    surname  varchar(30)  NOT NULL,
    position varchar(30)  NOT NULL,
    login    varchar(30)  NOT NULL,
    password varchar(100) NOT NULL,
    roles    varchar(100) NOT NULL,
    unit_id  int          REFERENCES unit (id) ON DELETE SET NULL
);

create table plant
(
    id           int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model        varchar(30) NOT NULL,
    location     varchar(30) NOT NULL,
    productivity int,
    unit_id      int         REFERENCES unit (id) ON DELETE SET NULL
);

create table hot_mix_test_result
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dno      decimal(6, 2),
    chog0063 decimal(6, 2),
    chog0125 decimal(6, 2),
    chog025  decimal(6, 2),
    chog05   decimal(6, 2),
    chog1    decimal(6, 2),
    chog2    decimal(6, 2),
    chog4    decimal(6, 2),
    chog56   decimal(6, 2),
    chog8    decimal(6, 2),
    chog112  decimal(6, 2),
    chog16   decimal(6, 2),
    chog224  decimal(6, 2),
    chog315  decimal(6, 2),
    gravity_mix_bulk      decimal(4, 3),
    gravity_mix_maximum      decimal(4, 3),
    batch_id int REFERENCES batch (id) ON DELETE CASCADE
);

create table recipe
(
    id                  int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    create_date         timestamp,
    modify_date         timestamp,
    mix_type            varchar(5),
    mix_layer           varchar(5),
    mix_traffic         varchar(5),
    stone_coarse1       varchar,
    stone_coarse2       varchar,
    stone_coarse3       varchar,
    stone_coarse4       varchar,
    stone_coarse5       varchar,
    stone_coarse6       varchar,
    stone_fine1         varchar,
    stone_fine2         varchar,
    powder              varchar,
    bitumen             varchar,
    additive1           varchar,
    additive2           varchar,
    PP0063              decimal(5, 2),
    PP0125              decimal(5, 2),
    PP025               decimal(5, 2),
    PP05                decimal(5, 2),
    PP1                 decimal(5, 2),
    PP2                 decimal(5, 2),
    PP4                 decimal(5, 2),
    PP56                decimal(5, 2),
    PP8                 decimal(5, 2),
    PP112               decimal(5, 2),
    PP16                decimal(5, 2),
    PP224               decimal(5, 2),
    PP315               decimal(5, 2),
    gravity_mix_bulk    decimal(4, 3),
    gravity_mix_maximum decimal(4, 3),
    water_resistance    decimal(3, 2),
    track_depth         decimal(2, 1),
    unit_id             int REFERENCES unit (id) ON DELETE CASCADE
);

create table batch
(
    id           int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    create_date  timestamp,
    modify_date  timestamp,
    quantity     decimal(7, 3),
    user_id      int         REFERENCES users (id) ON DELETE SET NULL,
    unit_id      int         REFERENCES unit (id) ON DELETE SET NULL,
    plant_id      int         REFERENCES plant (id) ON DELETE SET NULL,
    recipe_id      int         REFERENCES recipe (id) ON DELETE SET NULL

);









